### PR TITLE
[JENKINS-26611] SvnTagPublisher aborted java.lang.NoSuchMethodError

### PR DESCRIPTION
**Pull request by recena**
https://issues.jenkins-ci.org/browse/JENKINS-26611

This PR is related to this [PR](https://github.com/jenkinsci/svn-tag-plugin/pull/10). I've created this new PR to include only changes that solve the bug.

### CODE REVIEW

**Comment by recena** [comment]
@reviewbybees Could you review these changes? Specially, @stephenc and @daniel-beck

**Comment by christ66** [comment]
:bee:

**Comment by stephenc** [comment]
:bee:

**Comment by recena** [comment]
@christ66 @stephenc Thanks so much for your time.

**Comment by recena** [comment]
@reviewbybees done

**Pull request merged**
